#!/bin/sh
# Build each agent tool's global instruction file from shared + per-machine rules.
#   shared : <this repo>/global/shared-agents-rules.md   (synced by git)
#   machine: ~/.agents/machine-rules.md                  (real file, never leaves the machine; optional)
# Usage: global/sync-shared-agents-rules.sh [--force]
#   --force  overwrite a target that was not generated by this script (a .bak copy is kept)
# POSIX sh only (no bashisms): run it directly, or with sh / bash / zsh / dash / ksh.
# From fish or any other shell, execute it (./sync-shared-agents-rules.sh); do not source it.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
shared="$here/shared-agents-rules.md"
machine="$HOME/.agents/machine-rules.md"
marker="<!-- GENERATED by skills-marketplace/global/sync-shared-agents-rules.sh"
force=0
if [ "${1:-}" = "--force" ]; then force=1; fi

[ -f "$shared" ] || { echo "missing $shared" >&2; exit 1; }

mkdir -p "$HOME/.agents"
ln -sfn "$shared" "$HOME/.agents/shared-agents-rules.md"
# drop the symlink name used before the rename
if [ -L "$HOME/.agents/shared-rules.md" ]; then rm "$HOME/.agents/shared-rules.md"; fi

build() {
  printf '%s. Do not edit here.\n' "$marker"
  printf '     Shared rules: ~/.agents/shared-agents-rules.md (git). This machine: ~/.agents/machine-rules.md. -->\n\n'
  cat "$shared"
  if [ -s "$machine" ]; then printf '\n'; cat "$machine"; fi
}

write() { # <tool dir> <file name>
  w_dir=$1
  w_target="$1/$2"
  if [ ! -d "$w_dir" ]; then echo "skip  $w_target (tool not installed)"; return 0; fi
  if [ -s "$w_target" ] && ! grep -qF "<!-- GENERATED by skills-marketplace/global/" "$w_target"; then
    if [ "$force" -eq 1 ]; then
      cp "$w_target" "$w_target.bak-$(date +%Y%m%d%H%M%S)"
    else
      echo "KEEP  $w_target (hand-written; fold it into shared/machine rules, then rerun with --force)"
      return 0
    fi
  fi
  build > "$w_target.tmp" && mv "$w_target.tmp" "$w_target"
  echo "wrote $w_target"
}

write "$HOME/.claude" CLAUDE.md
write "$HOME/.codex"  AGENTS.md
write "$HOME/.gemini" GEMINI.md
