#!/usr/bin/env bash
# Build each agent tool's global instruction file from shared + per-machine rules.
#   shared : <this repo>/global/shared-rules.md   (synced by git)
#   machine: ~/.agents/machine-rules.md           (real file, never leaves the machine; optional)
# Usage: global/sync-rules.sh [--force]
#   --force  overwrite a target that was not generated by this script (a .bak copy is kept)
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
shared="$here/shared-rules.md"
machine="$HOME/.agents/machine-rules.md"
marker="<!-- GENERATED by skills-marketplace/global/sync-rules.sh"
force=0; [ "${1:-}" = "--force" ] && force=1

mkdir -p "$HOME/.agents"
ln -sfn "$shared" "$HOME/.agents/shared-rules.md"

build() {
  printf '%s. Do not edit here.\n     Shared rules: ~/.agents/shared-rules.md (git). This machine: ~/.agents/machine-rules.md. -->\n\n' "$marker"
  cat "$shared"
  if [ -s "$machine" ]; then printf '\n'; cat "$machine"; fi
}

write() { # <tool dir> <file name>
  local dir="$1" target="$1/$2"
  [ -d "$dir" ] || { echo "skip  $target (tool not installed)"; return; }
  if [ -s "$target" ] && ! grep -qF "$marker" "$target"; then
    if [ "$force" -eq 1 ]; then cp "$target" "$target.bak-$(date +%Y%m%d%H%M%S)"
    else echo "KEEP  $target (hand-written; fold it into shared/machine rules, then rerun with --force)"; return; fi
  fi
  build > "$target.tmp" && mv "$target.tmp" "$target"
  echo "wrote $target"
}

write "$HOME/.claude" CLAUDE.md
write "$HOME/.codex"  AGENTS.md
write "$HOME/.gemini" GEMINI.md
